import { storiesOf } from '@kadira/storybook'
import MenuPopupSection from './MenuPopupSection'

let items = [
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.member.list",
        "menuSearchName": "menu.member.list.individuals",
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/member-list?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "DEFAULT" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:63"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.request.records",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/request?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "MOVE_RECORDS" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:64"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.move.out",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/move-out?lang=eng",
        "urlInNewWindow": false,
        "uiSref": "move-out.find-member({lang: 'eng', href: '/mls/mbr/records/move-out-members?lang=eng'})",
        "uiSrefOpts": "{reload: true}",
        "liClass": null,
        "includeRoles": [ [ "MOVE_RECORDS" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:65"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.boundary.realignment",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/split-unit?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "MOVE_RECORDS" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:66"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.manage.oou.members",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/out-of-unit-members?lang=eng",
        "urlInNewWindow": false,
        "uiSref": "ooum.find-member({lang: 'eng', href: '/mls/mbr/records/out-of-unit-members?lang=eng'})",
        "uiSrefOpts": "{reload: true}",
        "liClass": null,
        "includeRoles": [ [ "MOVE_RECORDS" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:67"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.membership.audit",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/mbr-audit?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [
            [ "DEFAULT" ],
            [ "WARD", "BRANCH" ]
        ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:68"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.ordinances",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/ordinances?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "RECORD_EDIT", "PRINT_CERTIFICATES_AND_INTERVIEW_FORMS" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:69"
    },
    {
        "hiddenMenuSearchOnly": true,
        "name": "common.baptism.confirmation",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/ordinances/baptism?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "RECORD_EDIT", "PRINT_CERTIFICATES_AND_INTERVIEW_FORMS" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:70"
    },
    {
        "hiddenMenuSearchOnly": true,
        "name": "ord.record.priesthood.ord",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/ordinances/priesthood?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "RECORD_EDIT", "PRINT_CERTIFICATES_AND_INTERVIEW_FORMS" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:71"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.record.death",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/death?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "RECORD_EDIT" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:72"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.merge.duplicate",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/merge-duplicate?lang=eng",
        "urlInNewWindow": false,
        "uiSref": null,
        "uiSrefOpts": null,
        "liClass": null,
        "includeRoles": [ [ "RECORD_EDIT" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:73"
    },
    {
        "hiddenMenuSearchOnly": false,
        "name": "menu.create.record",
        "menuSearchName": null,
        "title": null,
        "parentTitle": "menu.records",
        "url": "/mls/mbr/records/create-start?lang=eng",
        "urlInNewWindow": false,
        "uiSref": "create-start({lang: 'eng', href: '/mls/mbr/records/create-start?lang=eng'})",
        "uiSrefOpts": "{reload: true}",
        "liClass": "new-feature",
        "includeRoles": [ [ "RECORD_EDIT" ] ],
        "excludeRoles": null,
        "subOrgId": null,
        "$$hashKey": "object:74"
    }
]


storiesOf('MenuPopupSection', module)

    .add('default', () => (<MenuPopupSection className="" items={items}/>))
