import { storiesOf, action } from '@kadira/storybook'
import MenuPopup from './MenuPopup'

const mainMenuOption =
    {
        "type": null,
        "hiddenMenuSearchOnly": false,
        "name": "menu.membership",
        "liClass": null,
        "ulClass": null,
        "allowEmptyMenu": false,
        "includeRoles": null,
        "excludeRoles": null,
        "item": null,
        "items": null,
        "columns": [
            [
                {
                    "type": null,
                    "hiddenMenuSearchOnly": false,
                    "name": "menu.records",
                    "liClass": null,
                    "ulClass": null,
                    "allowEmptyMenu": false,
                    "includeRoles": null,
                    "excludeRoles": null,
                    "item": null,
                    "items": [
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.member.list",
                            "menuSearchName": "menu.member.list.individuals",
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/member-list?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "DEFAULT" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:63"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.request.records",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/request?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "MOVE_RECORDS" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:64"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.move.out",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/move-out?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": "move-out.find-member({lang: 'eng', href: '/mls/mbr/records/move-out-members?lang=eng'})",
                            "uiSrefOpts": "{reload: true}",
                            "liClass": null,
                            "includeRoles": [ [ "MOVE_RECORDS" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:65"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.boundary.realignment",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/split-unit?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "MOVE_RECORDS" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:66"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.manage.oou.members",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/out-of-unit-members?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": "ooum.find-member({lang: 'eng', href: '/mls/mbr/records/out-of-unit-members?lang=eng'})",
                            "uiSrefOpts": "{reload: true}",
                            "liClass": null,
                            "includeRoles": [ [ "MOVE_RECORDS" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:67"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.membership.audit",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/mbr-audit?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [
                                [ "DEFAULT" ],
                                [ "WARD", "BRANCH" ]
                            ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:68"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.ordinances",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/ordinances?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "RECORD_EDIT", "PRINT_CERTIFICATES_AND_INTERVIEW_FORMS" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:69"
                        },
                        {
                            "hiddenMenuSearchOnly": true,
                            "name": "common.baptism.confirmation",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/ordinances/baptism?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "RECORD_EDIT", "PRINT_CERTIFICATES_AND_INTERVIEW_FORMS" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:70"
                        },
                        {
                            "hiddenMenuSearchOnly": true,
                            "name": "ord.record.priesthood.ord",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/ordinances/priesthood?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "RECORD_EDIT", "PRINT_CERTIFICATES_AND_INTERVIEW_FORMS" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:71"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.record.death",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/death?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "RECORD_EDIT" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:72"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.merge.duplicate",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/merge-duplicate?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "RECORD_EDIT" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:73"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.create.record",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.records",
                            "url": "/mls/mbr/records/create-start?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": "create-start({lang: 'eng', href: '/mls/mbr/records/create-start?lang=eng'})",
                            "uiSrefOpts": "{reload: true}",
                            "liClass": "new-feature",
                            "includeRoles": [ [ "RECORD_EDIT" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:74"
                        }
                    ],
                    "columns": null,
                    "parentSubOrgType": null,
                    "parentSubOrgId": null,
                    "$$hashKey": "object:57"
                },
                {
                    "type": null,
                    "hiddenMenuSearchOnly": false,
                    "name": "menu.limited.use.recommends",
                    "liClass": null,
                    "ulClass": null,
                    "allowEmptyMenu": false,
                    "includeRoles": null,
                    "excludeRoles": null,
                    "item": null,
                    "items": [
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.issue.limited.use.recommends",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.limited.use.recommends",
                            "url": "/mls/mbr/recommend/limited-use-recommend?lang=eng&new",
                            "urlInNewWindow": false,
                            "uiSref": "limited-use-recommend({lang: 'eng', cid: '', href: '/mls/mbr/recommend/limited-use-recommend?lang=eng'})",
                            "uiSrefOpts": "{reload: true}",
                            "liClass": null,
                            "includeRoles": [
                                [ "FEATURE_LIMITED_USE" ],
                                [ "LIMITED_USE_RECOMMEND_EDIT" ]
                            ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:101"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.issue.limited.use.group.recommends",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.limited.use.recommends",
                            "url": "/mls/mbr/recommend/limited-use-group-recommend?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [
                                [ "FEATURE_LIMITED_USE" ],
                                [ "LIMITED_USE_RECOMMEND_EDIT" ]
                            ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:102"
                        }
                    ],
                    "columns": null,
                    "parentSubOrgType": null,
                    "parentSubOrgId": null,
                    "$$hashKey": "object:58"
                }
            ],
            [
                {
                    "type": null,
                    "hiddenMenuSearchOnly": false,
                    "name": "menu.confidential",
                    "liClass": null,
                    "ulClass": null,
                    "allowEmptyMenu": false,
                    "includeRoles": null,
                    "excludeRoles": null,
                    "item": null,
                    "items": [
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.actions.in.process",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.confidential",
                            "url": "/mls/mbr/ca?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "CA_USER" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:113"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "messages.menu.request.minutes",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.confidential",
                            "url": "/mls/mbr/ca/request-documents?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [
                                [ "FEATURE_READMISSION_AFTER_NAME_REMOVAL" ],
                                [ "REQUEST_MINUTES" ]
                            ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:114"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.disciplinary.councils",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.confidential",
                            "url": "/mls/mbr/ca/disciplinary-councils?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "RECONVENE" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:115"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.application.first.presidency",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.confidential",
                            "url": "/mls/mbr/ca/afp/member-lookup?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [
                                [ "FEATURE_AFP" ],
                                [ "START_AFP" ]
                            ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:116"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.name.removal",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.confidential",
                            "url": "/mls/mbr/ca/name-removal?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "NAME_REMOVAL" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:117"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.readmission.after.name.removal",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.confidential",
                            "url": "/mls/mbr/ca/readmission-after-name-removal?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [
                                [ "FEATURE_READMISSION_AFTER_NAME_REMOVAL" ],
                                [ "NAME_REMOVAL" ]
                            ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:118"
                        },
                        {
                            "hiddenMenuSearchOnly": false,
                            "name": "menu.confidential.member.information.report",
                            "menuSearchName": null,
                            "title": null,
                            "parentTitle": "menu.confidential",
                            "url": "/mls/mbr/ca/confidential-member-info?lang=eng",
                            "urlInNewWindow": false,
                            "uiSref": null,
                            "uiSrefOpts": null,
                            "liClass": null,
                            "includeRoles": [ [ "CMIR" ] ],
                            "excludeRoles": null,
                            "subOrgId": null,
                            "$$hashKey": "object:119"
                        }
                    ],
                    "columns": null,
                    "parentSubOrgType": null,
                    "parentSubOrgId": null,
                    "$$hashKey": "object:109"
                }
            ]
        ],
        "parentSubOrgType": null,
        "parentSubOrgId": null,
        "$$hashKey": "object:18"
    }


storiesOf('MenuPopup', module)

    .add('default', () => (<MenuPopup className="" menu={mainMenuOption}/>))
